### ISSUE TITLE
Make an option to suppress colors in diff viewing

### ISSUE THREAD

**Issue by werg** [error-central/diffenv#18]
And disable colors by default when sending to file with `-o`

**Comment by wanderingstan** [comment]
sorry. :(
```bash
~/code/diffenv$ diffenv -c https://raw.githubusercontent.com/error-central/diffenv/master/examples/stan-diffenv.yaml
Traceback (most recent call last):
  File "/usr/local/bin/diffenv-nopaging", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/stan/code/diffenv/bin/diffenv-nopaging", line 99, in <module>
    not args.no_color)
  File "/Users/stan/code/diffenv/diffenv/diffviewer.py", line 33, in display_diff
    yaml.dump(diff_nested(fromfile, tofile), buf)
  File "/Users/stan/code/diffenv/diffenv/diffviewer.py", line 80, in diff_nested
    result[key] = diff_nested(m1[key], m2.get(key))
  File "/Users/stan/code/diffenv/diffenv/diffviewer.py", line 80, in diff_nested
    result[key] = diff_nested(m1[key], m2.get(key))
  File "/Users/stan/code/diffenv/diffenv/diffviewer.py", line 77, in diff_nested
    if m1[key] == m2.get(key):
AttributeError: 'str' object has no attribute 'get'
```
