### ISSUE TITLE
Not finding the yaml object in `main`. 

### ISSUE THREAD

**Issue by wanderingstan** [error-central/diffenv#3]
It's not finding the yaml object in `main`. 

```bash
~/code/diffenv$ python3 setup.py develop
```

```bash
~/code/diffenv$ diffenv
Traceback (most recent call last):
  File "/usr/local/bin/diffenv-nopaging", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/stan/code/diffenv/bin/diffenv-nopaging", line 63, in <module>
    main.yaml.dump(env, outfilestream)
AttributeError: module 'diffenv.main' has no attribute 'yaml'
```

**Comment by werg** [comment]
I actually can't reproduce this... If only there were a tool to compare our environments
