### ISSUE TITLE
Can't run diffenv

### ISSUE THREAD

**Issue by tyleryasaka** [error-central/diffenv#33]
Digging the concept! Looking forward to trying this out. Just ran into a snag.

**Describe the bug**

Could be something dumb like my Python3 not being set up right, I didn't try very hard 🤷‍♂. I would show you my diffenv, but... the command itself is failing for me 🙁 .

```
Traceback (most recent call last):
  File "/usr/local/bin/diffenv", line 174, in <module>
    env = main.collect_env(facets, whitelist)
  File "/usr/local/lib/python3.7/site-packages/diffenv/main.py", line 142, in collect_env
    facets[subdir] = collect_env(facets[subdir], whitelist[subdir])
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/comments.py", line 752, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'python'
```
**To Reproduce**
1. Clone repo
2. `python3 -m pip install diffenv`
3. `diffenv`

**Comment by werg** [comment]
Hi! Thank you so much for trying it out and reporting!
This commit may have fixed it:
https://github.com/error-central/diffenv/commit/cf2391241e25dd16d628a128e1ce158c7a116813

Could you try running

```bash
python3 -m pip uninstall diffenv
python3 -m pip install diffenv
diffenv
```
Thank you again @tyleryasaka !

**Comment by werg** [comment]
Hey @tyleryasaka did this fix your issue?
